[package]
name = "d23-a-long-walk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
aoc_toolbox = { path = "../aoc_toolbox/" }
itertools = "0.12.0"
chrono = "0.4.31"
